# Generated by Django 5.1.3 on 2024-11-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockQuantity', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='products/')),
                ('status', models.CharField(default='in stock', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('farmerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
            options={
                'db_table': 'tblProduct',
            },
        ),
    ]
