# Generated by Django 5.1.3 on 2024-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('targetId', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tblAdminActivityLog',
            },
        ),
    ]
