# Generated by Django 5.1.3 on 2024-11-20 03:44

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=50),
        ),
    ]
